name: disconx
description: DisConX - DICT Secure Connect Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.7
  firebase_analytics: ^11.3.6
  firebase_performance: ^0.10.0+11
  firebase_messaging: ^15.1.5
  
  # Networking
  dio: ^5.4.0
  connectivity_plus: ^6.1.4
  network_info_plus: ^6.0.0
  
  # Location Services
  geolocator: ^14.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Permissions
  permission_handler: ^12.0.0+1
  
  # Wi-Fi Scanning
  wifi_scan: ^0.4.1
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  package_info_plus: ^8.3.0
  
  # UI Enhancements
  shimmer: ^3.0.0
  flutter_animate: ^4.3.0
  badges: ^3.1.1
  
  # QR Code Scanner (for future features)
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  # Uncomment and add custom fonts if needed
  # fonts:
  #   - family: SFProDisplay
  #     fonts:
  #       - asset: fonts/SF-Pro-Display-Regular.ttf
  #       - asset: fonts/SF-Pro-Display-Medium.ttf
  #         weight: 500
  #       - asset: fonts/SF-Pro-Display-Bold.ttf
  #         weight: 700